sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
cache:
  directories:
  - packages/asyncmodule-import/node_modules
  - packages/inline-assets-chunks/node_modules
  - packages/react-asyncmodule/node_modules
  - packages/react-asyncmodule-tool/node_modules
before_script:
  - lerna bootstrap
after_success:
  - cat ./packages/react-asyncmodule/coverage/lcov.info | ./node_modules/.bin/coveralls